name: Test MY_ENV_VARIABLE

on:
  workflow_dispatch:

jobs:
  test-environment-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Environment Variable
        env:
          MY_ENV_VARIABLE: ${{ secrets.MY_ENV_VARIABLE }}
        run: |
          if [ -z "$MY_ENV_VARIABLE" ]; then
            echo "MY_ENV_VARIABLE is empty or not set."
          else
            echo "MY_ENV_VARIABLE is set to: $MY_ENV_VARIABLE"
          fi
