name: Testingss MY_ENV_VARIABLE

on:
  workflow_dispatch: # You can manually trigger the workflow

jobs:
  test-environment-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Printssas the environment variable
        env:
          MY_ENV_VARIABLE: ${{ secrets.MY_ENV_VARIABLE }}  # Access secret here
        run: |
          echo "MY_ENV_VARIABLE is set to: $MY_ENV_VARIABLE"
          
          # Check if the variable is empty or not
          if [ -z "$MY_ENV_VARIABLE" ]; then
            echo "MY_ENV_VARIABLE is empty or not set."
          else
            echo "MY_ENV_VARIABLE is set." $MY_ENV_VARIABLE
          fi
